import Head from 'next/head'
import styles from '../styles/Home.module.css'
import App from './App'


function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ToDO App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <App /> 
      
    </div>
  )
}


export default Home;


